name: arima
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.5
  - pandas=1.3.5
  - scipy=1.7.3
  - scikit-learn=1.0.1
  - statsmodels=0.13.1
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - patsy=0.5.2
  - pmdarima=1.8.5
  - h5py=3.6.0
  - protobuf=3.19.1
  - grpcio=1.43.0
  - six=1.16.0
  - typing-extensions=4.0.1
  - pip
  - pip:
      - tensorflow==2.7.0
      - keras==2.7.0
      - tensorflow-estimator==2.7.0
      - tensorboard==2.7.0
      - tensorflow-io-gcs-filesystem==0.23.1
      - absl-py==1.0.0
      - astunparse==1.6.3
      - opt-einsum==3.3.0
      - wrapt==1.13.3
      - termcolor==1.1.0
      - gast==0.4.0
      - google-pasta==0.2.0
      - libclang==13.0.0